remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: BEHeder's Website
description: Construction Site - Please wait for content to be added. Thank you for your patience!
